-- SCHEMA BUSINESS
-- AUTOR: WILMAN ORTIZ
-- FECHA: 14 ENERO 2017

-- ELIMINANDO BASE DE DATOS

DROP DATABASE IF EXISTS BUSINESS;

-- CREANDO BASE DE DATOS

CREATE DATABASE BUSINESS;

USE BUSINESS;

-- CREANDO TABLAS

CREATE TABLE CLIENTES(
    ID_CLIENTE BIGINT NOT NULL,
    CEDULA BIGINT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(100),
    FECHA_NACIMIENTO DATE,
    TELEFONO VARCHAR(30),
    EMAIL VARCHAR(100) NOT NULL,
    ID_IMG BIGINT
);
 
CREATE TABLE PRODUCTO(
    ID_PRODUCTO BIGINT NOT NULL,
    CODIGO VARCHAR(100) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    PRECIO BIGINT NOT NULL,
    STOCK BIGINT NOT NULL
);
 
CREATE TABLE FACTURA(
    NUMERO_FACTURA BIGINT NOT NULL,
    FECHA DATE NOT NULL,
    ID_CLIENTE BIGINT NOT NULL
);
 
CREATE TABLE DETALLE_FACTURA(
    NUM_DETALLE BIGINT NOT NULL,
    NUMERO_FACTURA BIGINT NOT NULL,
    ID_PRODUCTO BIGINT NOT NULL,
    CANTIDAD BIGINT NOT NULL,
    PRECIO BIGINT NOT NULL
);

CREATE TABLE IMAGEN(
    ID_IMAGEN BIGINT NOT NULL,
    IMG_PATH VARCHAR(512) NOT NULL,
    IMG_NAME VARCHAR(256) NOT NULL,
    IMG_SIZE VARCHAR(100) NOT NULL,
    IMG_TYPE VARCHAR(100) NOT NULL
);

-- AGREGANDO CONSTRAINTS

ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE); 
ALTER TABLE CLIENTES ADD CONSTRAINT CLIENTE_CC_UK UNIQUE (CEDULA);
ALTER TABLE CLIENTES CHANGE ID_CLIENTE ID_CLIENTE BIGINT AUTO_INCREMENT;

ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_COD_UK UNIQUE (CODIGO);
ALTER TABLE PRODUCTO CHANGE ID_PRODUCTO ID_PRODUCTO BIGINT AUTO_INCREMENT;

ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_PK PRIMARY KEY (NUMERO_FACTURA);
ALTER TABLE FACTURA CHANGE NUMERO_FACTURA NUMERO_FACTURA BIGINT AUTO_INCREMENT;

ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT DETALLE_FACTURA_PK PRIMARY KEY (NUM_DETALLE, NUMERO_FACTURA);

ALTER TABLE IMAGEN ADD CONSTRAINT IMAGEN_PK PRIMARY KEY (ID_IMAGEN);
ALTER TABLE IMAGEN CHANGE ID_IMAGEN ID_IMAGEN BIGINT AUTO_INCREMENT;

ALTER TABLE CLIENTES ADD CONSTRAINT IMAGEN_FK FOREIGN KEY (ID_IMG) REFERENCES IMAGEN (ID_IMAGEN);
ALTER TABLE FACTURA ADD CONSTRAINT CLIENTE_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE);
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FACTURA_DETALLE_FK FOREIGN KEY (NUMERO_FACTURA) REFERENCES FACTURA(NUMERO_FACTURA);
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT PRODUCTO_DETALLE_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);

-- INSERTANDO DATOS

INSERT INTO CLIENTES (CEDULA,NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL,ID_IMG) VALUES ('123456','Juan','Perez','Calle 123',STR_TO_DATE('05-07-93','%d-%m-%Y'),'03166178398','karlos@hotmail.com',null);
INSERT INTO CLIENTES (CEDULA,NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL,ID_IMG) VALUES ('789987','Alvaro','Otalora','Calle 456',STR_TO_DATE('05-07-10','%d-%m-%Y'),'987654','gene@gmail.com',null);
INSERT INTO CLIENTES (CEDULA,NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL,ID_IMG) VALUES ('4567654999','Pibe','Valderrama','Calle XYZ',STR_TO_DATE('04-07-12','%d-%m-%Y'),'87654377','chary123@hotmail.com',null);
INSERT INTO CLIENTES (CEDULA,NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL,ID_IMG) VALUES ('9191919','Tino','Asprilla','Calle 321',STR_TO_DATE('03-03-40','%d-%m-%Y'),'765432','ram@yahoo.es',null);
INSERT INTO CLIENTES (CEDULA,NOMBRE,APELLIDO,DIRECCION,FECHA_NACIMIENTO,TELEFONO,EMAIL,ID_IMG) VALUES ('9292923','Andres','Iniesta','Cra 123',STR_TO_DATE('19-09-84','%d-%m-%Y'),'876543','maria@hotmail.com',null);
 
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('001','BOARD INTEL MODELO 2015',300000,35);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('002','BOARD ASUS MODELO 2015',500000,20);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('003','BOARD MSI MODELO 2015',400000,15);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('004','TECLADO ASUS ROG MODELO 2015',30000,50);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('005','TECLADO MSI GAMER MODELO 2015',45000,10);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('006','TECLADO BASICO MODELO 2015',20000,20);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('007','MOUSE GENIUS MODELO 2015',13000,50);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('008','MOUSE GENIUS GAMER MODELO 2015',80000,5);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('009','MEMORIA USB 8 GB',15000,12);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0010','MEMORIA USB 16 GB',30000,35);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0011','MEMORIA USB 32 GB',45000,25);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0012','MEMORIA RAM 4 GB',70000,9);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0013','MEMORIA RAM 8 GB',110000,7);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0014','MEMORIA RAM 16 GB',200000,4);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0015','MONITOR SANSUMG 15 PULGADAS',300000,18);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0016','MONITOR LG 15 PULGADAS',700000,10);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0017','PORTATIL HP 1870',1200000,3);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0018','PORTATIL ASUS GX500',5560000,2);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0019','PORTATIL LENOVO THINKPAD',1800000,4);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0020','DISCO DURO EXTERNO HITACHI 2 TB',200000,20);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0021','DISCO DURO EXTERNO SANSUMG 1 TB',180000,15);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0022','DISCO DURO EXTERNO INTEL 512 GB',120000,35);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0023','CELULAR SANSUMG S6',2600000,11);
INSERT INTO PRODUCTO (CODIGO, NOMBRE, PRECIO, STOCK) VALUES ('0024','CELULAR XIAOMI MI NOTE PRO',1860000,4);
 
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('29-09-16','%d-%m-%Y'),'1');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('07-09-16','%d-%m-%Y'),'1');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('10-09-16','%d-%m-%Y'),'1');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('05-09-16','%d-%m-%Y'),'1');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('01-09-16','%d-%m-%Y'),'2');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('04-09-16','%d-%m-%Y'),'2');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('14-09-16','%d-%m-%Y'),'2');
INSERT INTO FACTURA (FECHA,ID_CLIENTE) VALUES (STR_TO_DATE('23-09-16','%d-%m-%Y'),'2');
 
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('1','1','2','3','10000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('2','1','4','2','50000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('3','1','6','4','6600');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('4','2','1','1','56200');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('5','2','7','5','23000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('6','3','10','1','45000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('7','3','11','4','60000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('8','3','8','7','15000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('9','4','20','1','100000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('10','5','4','2','90000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('11','5','6','2','7000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('12','6','18','11','30000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('13','6','19','2','64000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('14','7','9','3','85000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('15','8','14','6','90000');
INSERT INTO DETALLE_FACTURA (NUM_DETALLE,NUMERO_FACTURA,ID_PRODUCTO,CANTIDAD,PRECIO) VALUES ('16','8','13','7','75300');

/* 
CREATE OR REPLACE PACKAGE PKG_VENTAS IS
 PROCEDURE SP_OBTENER_CEDULA(ipNOMBRE IN VARCHAR, opCEDULA OUT NUMBER);
 PROCEDURE SP_CONSULTA_USUARIOS(opLISTADO OUT SYS_REFCURSOR, ipTIPO IN VARCHAR);
END;
/
 
CREATE OR REPLACE PACKAGE BODY PKG_VENTAS IS
 
 PROCEDURE SP_OBTENER_CEDULA(ipNOMBRE IN VARCHAR, opCEDULA OUT NUMBER) AS
 BEGIN
    SELECT C.CEDULA INTO opCEDULA
    FROM CLIENTES C
    WHERE C.NOMBRE LIKE '%' || ipNOMBRE || '%';
 EXCEPTION
    WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR SP_OBTENER_CEDULA');
 END;
 
 PROCEDURE SP_CONSULTA_USUARIOS(opLISTADO OUT SYS_REFCURSOR, ipTIPO IN VARCHAR) AS
 BEGIN
    OPEN opLISTADO FOR
     SELECT c.cedula,
            c.nombre,
            c.apellido,
            im.img_path,
            im.img_name
     FROM Clientes c INNER JOIN (SELECT i.id_imagen codigo,
                                        i.img_path,
                                        i.img_name
                                 FROM Imagen i
                                 WHERE i.img_type = ipTIPO) im ON (c.id_img = im.codigo);
 EXCEPTION
      WHEN OTHERS THEN
           DBMS_OUTPUT.PUT_LINE('ERROR EJECUTANDO EL PROCEDIMIENTO');
 END;
END;
*/