-- MySQL Script generated by MySQL Workbench
-- 04/16/17 18:21:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema politica
-- -----------------------------------------------------
-- Base de datos diseñada para llevar control de la gestión de personas que apoyan una campaña
DROP SCHEMA IF EXISTS `politica` ;

-- -----------------------------------------------------
-- Schema politica
--
-- Base de datos diseñada para llevar control de la gestión de personas que apoyan una campaña
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `politica` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `politica` ;

-- -----------------------------------------------------
-- Table `politica`.`tbl_sec_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_sec_user` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_sec_user` (
  `user_key` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(256) NULL,
  `cedula` BIGINT(255) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `celular` MEDIUMTEXT NOT NULL,
  `fecha_nacimiento` DATETIME NULL,
  PRIMARY KEY (`user_key`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cedula_UNIQUE` ON `politica`.`tbl_sec_user` (`cedula` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_sec_roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_sec_roles` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_sec_roles` (
  `rol_key` INT NOT NULL AUTO_INCREMENT,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_key`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rol_UNIQUE` ON `politica`.`tbl_sec_roles` (`rol` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_sec_permissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_sec_permissions` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_sec_permissions` (
  `permission_key` INT NOT NULL AUTO_INCREMENT,
  `permiso_menu` INT NULL,
  `permiso_crear_usuarios` INT NULL,
  `permiso_consultar_usuarios` INT NULL,
  `permiso_actualizar_usuarios` INT NULL,
  `permiso_eliminar_usuarios` INT NULL,
  PRIMARY KEY (`permission_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbls_sec_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbls_sec_detail` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbls_sec_detail` (
  `user_key` INT NOT NULL,
  `rol_key` INT NOT NULL,
  `permission_key` INT NOT NULL,
  PRIMARY KEY (`user_key`, `rol_key`, `permission_key`),
  CONSTRAINT `fk_tbls_sec_detail_tbl_sec_user`
    FOREIGN KEY (`user_key`)
    REFERENCES `politica`.`tbl_sec_user` (`user_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbls_sec_detail_tbl_sec_roles`
    FOREIGN KEY (`rol_key`)
    REFERENCES `politica`.`tbl_sec_roles` (`rol_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbls_sec_detail_tbl_sec_permissions`
    FOREIGN KEY (`permission_key`)
    REFERENCES `politica`.`tbl_sec_permissions` (`permission_key`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_tbls_sec_detail_tbl_sec_roles_idx` ON `politica`.`tbls_sec_detail` (`rol_key` ASC);

CREATE INDEX `fk_tbls_sec_detail_tbl_sec_permissions_idx` ON `politica`.`tbls_sec_detail` (`permission_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_estado_civil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_estado_civil` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_estado_civil` (
  `estado_key` INT NOT NULL AUTO_INCREMENT,
  `nombre_estado` VARCHAR(100) NULL,
  PRIMARY KEY (`estado_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_nivel_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_nivel_estudios` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_nivel_estudios` (
  `nivel_estudio_key` INT NOT NULL AUTO_INCREMENT,
  `nombre_estudios` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nivel_estudio_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_otros_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_otros_estudios` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_otros_estudios` (
  `otros_estudios_key` INT NOT NULL AUTO_INCREMENT,
  `nombre_otros` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`otros_estudios_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_caracter_entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_caracter_entidad` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_caracter_entidad` (
  `caracter_key` INT NOT NULL AUTO_INCREMENT,
  `caracter_entidad` VARCHAR(100) NULL,
  PRIMARY KEY (`caracter_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_negocio_votante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_negocio_votante` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_negocio_votante` (
  `votante_key` INT NOT NULL AUTO_INCREMENT,
  `cedula` BIGINT(80) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `lugar_nacimiento` VARCHAR(100) NOT NULL,
  `direccion` VARCHAR(256) NOT NULL,
  `telefono` BIGINT(80) NULL,
  `celular` BIGINT(80) NOT NULL,
  `email` VARCHAR(256) NULL,
  `estado_key` INT NOT NULL,
  PRIMARY KEY (`votante_key`, `estado_key`),
  CONSTRAINT `fk_votante_estado_civil`
    FOREIGN KEY (`estado_key`)
    REFERENCES `politica`.`tbl_param_estado_civil` (`estado_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_votante_estado_civil_idx` ON `politica`.`tbl_negocio_votante` (`estado_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_referencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_referencia` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_referencia` (
  `referencia_type_key` INT NOT NULL AUTO_INCREMENT,
  `referencia_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`referencia_type_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_negocio_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_negocio_estudios` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_negocio_estudios` (
  `estudio_key` INT NOT NULL AUTO_INCREMENT,
  `lugar_estudio` VARCHAR(256) NOT NULL,
  `titulo` VARCHAR(256) NOT NULL,
  `desde` DATETIME NOT NULL,
  `hasta` DATETIME NOT NULL,
  `nivel_estudio_key` INT NOT NULL,
  `votante_key` INT NOT NULL,
  PRIMARY KEY (`estudio_key`, `votante_key`, `nivel_estudio_key`),
  CONSTRAINT `fk_votante_estudios`
    FOREIGN KEY (`votante_key`)
    REFERENCES `politica`.`tbl_negocio_votante` (`votante_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_negocio_estudios_tbl_param_nivel_estudios1`
    FOREIGN KEY (`nivel_estudio_key`)
    REFERENCES `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_negocio_estudios_tbl_negocio_votante1_idx` ON `politica`.`tbl_negocio_estudios` (`votante_key` ASC);

CREATE INDEX `fk_tbl_negocio_estudios_tbl_param_nivel_estudios1_idx` ON `politica`.`tbl_negocio_estudios` (`nivel_estudio_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_otros_estudios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_otros_estudios` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_otros_estudios` (
  `otros_key` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `intensidad` INT NOT NULL,
  `votante_key` INT NOT NULL,
  `otros_estudios_key` INT NOT NULL,
  PRIMARY KEY (`otros_key`, `votante_key`, `otros_estudios_key`),
  CONSTRAINT `fk_votantes_otros`
    FOREIGN KEY (`votante_key`)
    REFERENCES `politica`.`tbl_negocio_votante` (`votante_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_otros_estudios`
    FOREIGN KEY (`otros_estudios_key`)
    REFERENCES `politica`.`tbl_param_otros_estudios` (`otros_estudios_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_votantes_otros_idx` ON `politica`.`tbl_otros_estudios` (`votante_key` ASC);

CREATE INDEX `fk_otros_estudios_idx` ON `politica`.`tbl_otros_estudios` (`otros_estudios_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_negocio_experiencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_negocio_experiencia` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_negocio_experiencia` (
  `experiencia_key` INT NOT NULL AUTO_INCREMENT,
  `desde` DATETIME NOT NULL,
  `hasta` DATETIME NOT NULL,
  `descripcion` VARCHAR(1000) NOT NULL,
  `votante_key` INT NOT NULL,
  `caracter_key` INT NOT NULL,
  PRIMARY KEY (`experiencia_key`, `votante_key`, `caracter_key`),
  CONSTRAINT `fk_votante_experiencia`
    FOREIGN KEY (`votante_key`)
    REFERENCES `politica`.`tbl_negocio_votante` (`votante_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_caracter`
    FOREIGN KEY (`caracter_key`)
    REFERENCES `politica`.`tbl_param_caracter_entidad` (`caracter_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_votante_experiencia_idx` ON `politica`.`tbl_negocio_experiencia` (`votante_key` ASC);

CREATE INDEX `fk_experiencia_caracter_idx` ON `politica`.`tbl_negocio_experiencia` (`caracter_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_negocio_referencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_negocio_referencias` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_negocio_referencias` (
  `referencia_key` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `ocupacion` VARCHAR(100) NOT NULL,
  `celular` BIGINT(100) NOT NULL,
  `votante_key` INT NOT NULL,
  `referencia_type_key` INT NOT NULL,
  PRIMARY KEY (`referencia_key`, `votante_key`, `referencia_type_key`),
  CONSTRAINT `fk_referencia_type`
    FOREIGN KEY (`referencia_type_key`)
    REFERENCES `politica`.`tbl_param_referencia` (`referencia_type_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votante_referencia`
    FOREIGN KEY (`votante_key`)
    REFERENCES `politica`.`tbl_negocio_votante` (`votante_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_votante_referencia_idx` ON `politica`.`tbl_negocio_referencias` (`votante_key` ASC);

CREATE INDEX `fk_referencia_type_idx` ON `politica`.`tbl_negocio_referencias` (`referencia_type_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_perfil` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_perfil` (
  `perfil_key` INT NOT NULL AUTO_INCREMENT,
  `nombre_perdil` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`perfil_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_param_subperfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_param_subperfil` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_param_subperfil` (
  `subperfil_key` INT NOT NULL AUTO_INCREMENT,
  `nombre_subperfil` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`subperfil_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `politica`.`tbl_negocio_detalle_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_negocio_detalle_perfil` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_negocio_detalle_perfil` (
  `detalle_perfil_key` INT NOT NULL AUTO_INCREMENT,
  `votante_key` INT NOT NULL,
  `perfil_key` INT NOT NULL,
  `subperfil_key` INT NOT NULL,
  `enfasis` TINYINT(1) NULL,
  `cual` VARCHAR(256) NULL,
  PRIMARY KEY (`detalle_perfil_key`, `subperfil_key`, `votante_key`, `perfil_key`),
  CONSTRAINT `fk_perfiles`
    FOREIGN KEY (`perfil_key`)
    REFERENCES `politica`.`tbl_param_perfil` (`perfil_key`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subperfil`
    FOREIGN KEY (`subperfil_key`)
    REFERENCES `politica`.`tbl_param_subperfil` (`subperfil_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votantes`
    FOREIGN KEY (`votante_key`)
    REFERENCES `politica`.`tbl_negocio_votante` (`votante_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_perfiles_idx` ON `politica`.`tbl_negocio_detalle_perfil` (`perfil_key` ASC);

CREATE INDEX `fk_subperfil_idx` ON `politica`.`tbl_negocio_detalle_perfil` (`subperfil_key` ASC);

CREATE INDEX `fk_votantes_idx` ON `politica`.`tbl_negocio_detalle_perfil` (`votante_key` ASC);


-- -----------------------------------------------------
-- Table `politica`.`tbl_sec_auditoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `politica`.`tbl_sec_auditoria` ;

CREATE TABLE IF NOT EXISTS `politica`.`tbl_sec_auditoria` (
  `auditoria_key` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATETIME NOT NULL,
  `fecha_salida` DATETIME NOT NULL,
  `user_key` INT NOT NULL,
  PRIMARY KEY (`auditoria_key`, `user_key`),
  CONSTRAINT `fk_user`
    FOREIGN KEY (`user_key`)
    REFERENCES `politica`.`tbl_sec_user` (`user_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_tbl_sec_auditoria_tbl_sec_user1_idx` ON `politica`.`tbl_sec_auditoria` (`user_key` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO politica;
 DROP USER politica;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'politica' IDENTIFIED BY 'politica20172018*';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `politica`.`tbl_sec_user`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_sec_user` (`user_key`, `usuario`, `password`, `cedula`, `nombres`, `apellidos`, `direccion`, `celular`, `fecha_nacimiento`) VALUES (DEFAULT, 'admin', 'Lx6Hg1cJVKI2jxHlramnlXl62U78o6Vh', 8649168, 'Carlos Andres', 'Ortiz Navarro', 'Cra 24 # 30 - 24', '3023375803', '1993-07-05');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_sec_roles`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_sec_roles` (`rol_key`, `rol`) VALUES (DEFAULT, 'ROLE_ADMIN');
INSERT INTO `politica`.`tbl_sec_roles` (`rol_key`, `rol`) VALUES (DEFAULT, 'ROLE_USER');
INSERT INTO `politica`.`tbl_sec_roles` (`rol_key`, `rol`) VALUES (DEFAULT, 'ROLE_GUEST');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_sec_permissions`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_sec_permissions` (`permission_key`, `permiso_menu`, `permiso_crear_usuarios`, `permiso_consultar_usuarios`, `permiso_actualizar_usuarios`, `permiso_eliminar_usuarios`) VALUES (DEFAULT, 1, 1, 1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbls_sec_detail`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbls_sec_detail` (`user_key`, `rol_key`, `permission_key`) VALUES (1, 1, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_estado_civil`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_estado_civil` (`estado_key`, `nombre_estado`) VALUES (DEFAULT, 'Soltero');
INSERT INTO `politica`.`tbl_param_estado_civil` (`estado_key`, `nombre_estado`) VALUES (DEFAULT, 'Casado');
INSERT INTO `politica`.`tbl_param_estado_civil` (`estado_key`, `nombre_estado`) VALUES (DEFAULT, 'Divorciado');
INSERT INTO `politica`.`tbl_param_estado_civil` (`estado_key`, `nombre_estado`) VALUES (DEFAULT, 'Union Libre');
INSERT INTO `politica`.`tbl_param_estado_civil` (`estado_key`, `nombre_estado`) VALUES (DEFAULT, 'Viudo');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_nivel_estudios`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Secundaria');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Tecnólogo');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Técnico');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Universitario');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Posgrado');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Maestría');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Magister');
INSERT INTO `politica`.`tbl_param_nivel_estudios` (`nivel_estudio_key`, `nombre_estudios`) VALUES (DEFAULT, 'Doctorado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_otros_estudios`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_otros_estudios` (`otros_estudios_key`, `nombre_otros`) VALUES (DEFAULT, 'Seminario');
INSERT INTO `politica`.`tbl_param_otros_estudios` (`otros_estudios_key`, `nombre_otros`) VALUES (DEFAULT, 'Curso');
INSERT INTO `politica`.`tbl_param_otros_estudios` (`otros_estudios_key`, `nombre_otros`) VALUES (DEFAULT, 'Diplomado');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_caracter_entidad`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_caracter_entidad` (`caracter_key`, `caracter_entidad`) VALUES (DEFAULT, 'Pública');
INSERT INTO `politica`.`tbl_param_caracter_entidad` (`caracter_key`, `caracter_entidad`) VALUES (DEFAULT, 'Privada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_referencia`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_referencia` (`referencia_type_key`, `referencia_nombre`) VALUES (DEFAULT, 'Personal');
INSERT INTO `politica`.`tbl_param_referencia` (`referencia_type_key`, `referencia_nombre`) VALUES (DEFAULT, 'Familiar');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_perfil`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_perfil` (`perfil_key`, `nombre_perdil`) VALUES (DEFAULT, 'Docente');
INSERT INTO `politica`.`tbl_param_perfil` (`perfil_key`, `nombre_perdil`) VALUES (DEFAULT, 'Profesional');
INSERT INTO `politica`.`tbl_param_perfil` (`perfil_key`, `nombre_perdil`) VALUES (DEFAULT, 'Oficios Varios');
INSERT INTO `politica`.`tbl_param_perfil` (`perfil_key`, `nombre_perdil`) VALUES (DEFAULT, 'Manipuladoras');

COMMIT;


-- -----------------------------------------------------
-- Data for table `politica`.`tbl_param_subperfil`
-- -----------------------------------------------------
START TRANSACTION;
USE `politica`;
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Sociales');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Lenguaje');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Naturales');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Matematicas');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Qumica');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Física');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Ingles');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Lic. Música');
INSERT INTO `politica`.`tbl_param_subperfil` (`subperfil_key`, `nombre_subperfil`) VALUES (DEFAULT, 'Normalista');

COMMIT;

