-- SCHEMA SECURITY
-- AUTOR: WILMAN ORTIZ
-- FECHA: 14 ENERO 2017
 
-- USER SQL
-- CREATE USER SECURITY IDENTIFIED BY security 
-- DEFAULT TABLESPACE "USERS"
-- TEMPORARY TABLESPACE "TEMP";

-- ROLES
-- GRANT "CONNECT" TO SECURITY ;
-- GRANT "RESOURCE" TO SECURITY ; 
 
-- ELIMINAR TABLAS
DROP TABLE USERS                CASCADE CONSTRAINTS;
DROP TABLE ROLES                CASCADE CONSTRAINTS;
DROP TABLE USERS_ROLES          CASCADE CONSTRAINTS;
DROP TABLE IMAGEN               CASCADE CONSTRAINTS;
DROP TABLE OAUTH_CLIENT_DETAILS CASCADE CONSTRAINTS;
DROP TABLE OAUTH_CLIENT_TOKEN   CASCADE CONSTRAINTS;
DROP TABLE OAUTH_ACCESS_TOKEN   CASCADE CONSTRAINTS;
DROP TABLE OAUTH_REFRESH_TOKEN  CASCADE CONSTRAINTS;
DROP TABLE OAUTH_CODE           CASCADE CONSTRAINTS;
DROP TABLE OAUTH_APPROVALS      CASCADE CONSTRAINTS;
DROP TABLE CLIENT_DETAILS       CASCADE CONSTRAINTS;

-- ELIMINAR SECUENCIAS
DROP SEQUENCE SQ_USERS;
DROP SEQUENCE SQ_ROLES;
DROP SEQUENCE SQ_IMAGEN;
 
-- DROP TRIGGER TRG_USERS;
-- DROP TRIGGER TRG_ROLES;
-- DROP TRIGGER TRG_PRODUCTO;
-- DROP TRIGGER TRG_FACTURA;
 
-- CREANDO TABLAS
CREATE TABLE USERS(
    ID_USER                NUMBER NOT NULL,
    CEDULA                 NUMBER NOT NULL,
    NOMBRE                 VARCHAR2(50) NOT NULL,
    APELLIDO               VARCHAR2(50) NOT NULL,
    DIRECCION              VARCHAR2(100),
    FECHA_NACIMIENTO       DATE,
    FECHA_INGRESO          DATE,
    FECHA_RETIRO           DATE,
    TELEFONO               VARCHAR2(30),
    EMAIL                  VARCHAR2(100) NOT NULL,
    LOGIN                  VARCHAR2(30) NOT NULL,
    PASSWORD               VARCHAR2(100) NOT NULL,
    ENABLE                 VARCHAR2(10),
    ACCOUNT_NON_EXPIRED    VARCHAR2(10),
    CREDENTIAL_NON_EXPIRED VARCHAR2(10),
    ACCOUNT_NON_LOCKED     VARCHAR2(10),
    ID_IMG                 NUMBER
);
 
CREATE TABLE ROLES(
    ID_ROLE NUMBER NOT NULL,
    ROLE    VARCHAR2(50) NOT NULL
);
 
CREATE TABLE USERS_ROLES(
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL
);
 
CREATE TABLE OAUTH_CLIENT_DETAILS (
       CLIENT_ID               VARCHAR2(255),
       CLIENT_NAME             VARCHAR2(255),
       RESOURCE_IDS            VARCHAR2(255),
       CLIENT_SECRET           VARCHAR2(255),
       SCOPE                   VARCHAR2(255),
       AUTHORIZED_GRANT_TYPES  VARCHAR2(255),
       WEB_SERVER_REDIRECT_URI VARCHAR2(255),
       AUTHORITIES             VARCHAR2(255),
       ACCESS_TOKEN_VALIDITY   NUMBER(10,0),
       REFRESH_TOKEN_VALIDITY  NUMBER(10,0),
       ADDITIONAL_INFORMATION  VARCHAR2(2000),
       AUTOAPPROVE             VARCHAR2(255)
);
 
CREATE TABLE OAUTH_CLIENT_TOKEN (
       AUTHENTICATION_ID VARCHAR2(255),
       TOKEN_ID  VARCHAR2(255),
       TOKEN     BLOB,
       USER_NAME VARCHAR2(255),
       CLIENT_ID VARCHAR2(255)
);
 
CREATE TABLE OAUTH_ACCESS_TOKEN (
       AUTHENTICATION_ID VARCHAR2(255),
       TOKEN_ID          VARCHAR2(255),
       TOKEN             BLOB,
       USER_NAME         VARCHAR2(255),
       CLIENT_ID         VARCHAR2(255),
       AUTHENTICATION    BLOB,
       REFRESH_TOKEN     VARCHAR2(255)
);
 
CREATE TABLE OAUTH_REFRESH_TOKEN (
       TOKEN_ID       VARCHAR2(255),
       TOKEN          BLOB,
       AUTHENTICATION BLOB
);
 
CREATE TABLE OAUTH_CODE (
       CODE           VARCHAR2(255),
       AUTHENTICATION BLOB
);
 
CREATE TABLE OAUTH_APPROVALS (
       USERID         VARCHAR2(255),
       CLIENTID       VARCHAR2(255),
       SCOPE          VARCHAR2(255),
       STATUS         VARCHAR2(10),
       EXPIRESAT      DATE,
       LASTMODIFIEDAT DATE
);
 
CREATE TABLE CLIENT_DETAILS (
       APPID                  VARCHAR2(255),
       RESOURCEIDS            VARCHAR2(255),
       APPSECRET              VARCHAR2(255),
       SCOPE                  VARCHAR2(255),
       GRANTTYPES             VARCHAR2(255),
       REDIRECTURL            VARCHAR2(255),
       AUTHORITIES            VARCHAR2(255),
       ACCESS_TOKEN_VALIDITY  NUMBER(10,0),
       REFRESH_TOKEN_VALIDITY NUMBER(10,0),
       ADDITIONALINFORMATION  VARCHAR2(2000),
       AUTOAPPROVESCOPES      VARCHAR2(255)
);
 
CREATE TABLE IMAGEN(
    ID_IMAGEN NUMBER NOT NULL,
    IMG_PATH  VARCHAR2(512) NOT NULL,
    IMG_NAME  VARCHAR2(256) NOT NULL,
    IMG_SIZE  VARCHAR2(100) NOT NULL,
    IMG_TYPE  VARCHAR2(100) NOT NULL
);
 
-- EJECUTANDO CONSTRAINT
ALTER TABLE USERS ADD CONSTRAINT USER_PK PRIMARY KEY (ID_USER);
 
ALTER TABLE USERS ADD CONSTRAINT USER_LG_UK UNIQUE (LOGIN);
ALTER TABLE USERS ADD CONSTRAINT USER_CC_UK UNIQUE (CEDULA);
 
ALTER TABLE ROLES ADD CONSTRAINT ROLE_PK PRIMARY KEY(ID_ROLE);
 
ALTER TABLE USERS_ROLES ADD CONSTRAINT USER_ROLE_PK PRIMARY KEY (USER_ID, ROLE_ID);
ALTER TABLE USERS_ROLES ADD CONSTRAINT USER_FK FOREIGN KEY (USER_ID) REFERENCES USERS(ID_USER);
ALTER TABLE USERS_ROLES ADD CONSTRAINT ROLE_FK FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID_ROLE);
 
ALTER TABLE IMAGEN ADD CONSTRAINT IMAGEN_PK PRIMARY KEY (ID_IMAGEN);
 
ALTER TABLE USERS ADD CONSTRAINT USER_IMAGEN_FK FOREIGN KEY (ID_IMG) REFERENCES IMAGEN(ID_IMAGEN);

ALTER TABLE OAUTH_CLIENT_DETAILS ADD CONSTRAINT OAUTH2_CLIENT_PK PRIMARY KEY (CLIENT_ID);

ALTER TABLE OAUTH_CLIENT_DETAILS ADD CONSTRAINT OAUTH2_CLIENT_UK UNIQUE (CLIENT_NAME);

ALTER TABLE OAUTH_CLIENT_TOKEN ADD CONSTRAINT OAUTH2_CLIENT_TOKEN_PK PRIMARY KEY (AUTHENTICATION_ID);

ALTER TABLE OAUTH_ACCESS_TOKEN ADD CONSTRAINT OAUTH2_ACCESS_TOKEN_PK PRIMARY KEY (AUTHENTICATION_ID);

ALTER TABLE OAUTH_APPROVALS ADD CONSTRAINT OAUTH_APPROVALS_PK PRIMARY KEY (USERID, CLIENTID);

ALTER TABLE CLIENT_DETAILS ADD CONSTRAINT CLIENT_DETAILS_PK PRIMARY KEY (APPID);

ALTER TABLE OAUTH_REFRESH_TOKEN ADD CONSTRAINT OAUTH_REFRESH_TOKEN_PK PRIMARY KEY (TOKEN_ID);
 
-- CREANDO SECUENCIAS
CREATE SEQUENCE SQ_USERS INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999 MINVALUE 1;
CREATE SEQUENCE SQ_ROLES INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999 MINVALUE 1;
CREATE SEQUENCE SQ_IMAGEN INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999999 MINVALUE 1;

-- CREANDO TRIGGERS
CREATE OR REPLACE TRIGGER TRG_USERS BEFORE INSERT ON USERS
 FOR EACH ROW
 BEGIN
    IF (:NEW.ID_USER IS NULL) THEN
        SELECT SQ_USERS.NEXTVAL INTO :NEW.ID_USER
        FROM DUAL;
    END IF;
 END;
/ 
 
CREATE OR REPLACE TRIGGER TRG_ROLES BEFORE INSERT ON ROLES
 FOR EACH ROW
 BEGIN
    IF (:NEW.ID_ROLE IS NULL) THEN
        SELECT SQ_ROLES.NEXTVAL INTO :NEW.ID_ROLE
        FROM DUAL;
    END IF;
 END;
/
 
CREATE OR REPLACE TRIGGER TRG_IMAGEN BEFORE INSERT ON IMAGEN
 FOR EACH ROW
 BEGIN
    IF (:NEW.ID_IMAGEN IS NULL) THEN
        SELECT SQ_IMAGEN.NEXTVAL INTO :NEW.ID_IMAGEN
        FROM DUAL;
    END IF;
 END;
/
 
-- HABILITANDO TRIGGERS 
ALTER TRIGGER TRG_USERS ENABLE;
ALTER TRIGGER TRG_ROLES ENABLE;
ALTER TRIGGER TRG_IMAGEN ENABLE;
 
-- INSERTANDO VALORES POR DEFECTO
INSERT INTO OAUTH_CLIENT_DETAILS (CLIENT_ID,CLIENT_NAME,RESOURCE_IDS,CLIENT_SECRET,SCOPE,AUTHORIZED_GRANT_TYPES,WEB_SERVER_REDIRECT_URI,AUTHORITIES,ACCESS_TOKEN_VALIDITY,REFRESH_TOKEN_VALIDITY,ADDITIONAL_INFORMATION,AUTOAPPROVE) VALUES ('clientapp','WebApp','microservice','987654321','read,write','password,refresh_token,client_credentials','http://localhost:8086/MicroServices/','USER','300','600',null,null);

 
INSERT INTO USERS(CEDULA, NOMBRE, APELLIDO, DIRECCION, FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_RETIRO, TELEFONO, EMAIL, LOGIN, PASSWORD, ENABLE, ACCOUNT_NON_EXPIRED, CREDENTIAL_NON_EXPIRED, ACCOUNT_NON_LOCKED, ID_IMG) VALUES (8649168, 'root', 'admin', 'Carrera 123', TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),3166178398,'root@gmail.com','root','$2a$10$tartLAsO2Bm8iMtrqdyQXua/CMZ3/8260G/c4OKza6DslRKexKSuW','true','true','true','true',null);
INSERT INTO USERS(CEDULA, NOMBRE, APELLIDO, DIRECCION, FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_RETIRO, TELEFONO, EMAIL, LOGIN, PASSWORD, ENABLE, ACCOUNT_NON_EXPIRED, CREDENTIAL_NON_EXPIRED, ACCOUNT_NON_LOCKED, ID_IMG) VALUES (1043000687, 'Juan', 'Ortiz', 'Av. Siempre viva 742', TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),3016394477,'jortiz@hotmail.com','jortiz','$2a$10$tartLAsO2Bm8iMtrqdyQXua/CMZ3/8260G/c4OKza6DslRKexKSuW','true','true','true','true',null);
INSERT INTO USERS(CEDULA, NOMBRE, APELLIDO, DIRECCION, FECHA_NACIMIENTO, FECHA_INGRESO, FECHA_RETIRO, TELEFONO, EMAIL, LOGIN, PASSWORD, ENABLE, ACCOUNT_NON_EXPIRED, CREDENTIAL_NON_EXPIRED, ACCOUNT_NON_LOCKED, ID_IMG) VALUES (123456789, 'Guest' , 'User', 'NOT_FOUND', TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),TO_DATE(SYSDATE,'dd/MM/yyyy'),3016390440,'guest@example.com','guest','$2a$10$tartLAsO2Bm8iMtrqdyQXua/CMZ3/8260G/c4OKza6DslRKexKSuW','true','true','true','true',null);
 
INSERT INTO ROLES(ROLE) VALUES ('ROLE_ADMIN');
INSERT INTO ROLES(ROLE) VALUES ('ROLE_USER');
INSERT INTO ROLES(ROLE) VALUES ('ROLE_GUEST');
 
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO USERS_ROLES(USER_ID, ROLE_ID) VALUES (3, 3);